// This file is auto-generated by @hey-api/openapi-ts

export const $UserProviderType = {
    enum: ['EMail'],
    title: 'Auth provider type',
    description: 'The type of the auth provider',
    type: 'string'
} as const;

export const $User = {
    type: 'object',
    properties: {
        id: {
            description: 'ID of the user',
            format: 'uuid',
            type: 'string'
        },
        givenName: {
            description: 'Given name of the user',
            type: 'string'
        },
        familyName: {
            description: 'Family name of the user',
            type: 'string'
        }
    },
    required: ['id', 'givenName', 'familyName'],
    title: 'User'
} as const;

export const $UserProvider = {
    type: 'object',
    properties: {
        userId: {
            description: 'ID of the user',
            format: 'uuid',
            type: 'string'
        },
        providerType: {
            enum: ['EMail'],
            title: 'Auth provider type',
            description: 'The type of the auth provider',
            type: 'string'
        },
        accountId: {
            description: 'The account id associated with the provider',
            type: 'string'
        }
    },
    required: ['userId', 'providerType', 'accountId'],
    title: 'UserProvider'
} as const;

export const $CreateEMailUserRequest = {
    type: 'object',
    properties: {
        givenName: {
            minLength: 1,
            maxLength: 50,
            type: 'string'
        },
        familyName: {
            minLength: 1,
            maxLength: 100,
            type: 'string'
        },
        email: {
            minLength: 3,
            maxLength: 255,
            format: 'email',
            type: 'string'
        },
        password: {
            minLength: 8,
            maxLength: 64,
            type: 'string'
        }
    },
    required: ['givenName', 'familyName', 'email', 'password'],
    title: 'CreateEMailUserRequest'
} as const;

export const $CreateEMailUserResponse = {
    type: 'object',
    properties: {
        user: {
            '$ref': '#/components/schemas/User'
        },
        provider: {
            '$ref': '#/components/schemas/UserProvider'
        }
    },
    required: ['user', 'provider'],
    title: 'CreateEMailUserResponse'
} as const;