// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { CreateEmailUserData, CreateEmailUserError, CreateEmailUserResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Create an e-mail-based account
 */
export const createEmailUser = <ThrowOnError extends boolean = false>(options?: Options<CreateEmailUserData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateEmailUserResponse, CreateEmailUserError, ThrowOnError>({
        ...options,
        url: '/users/email'
    });
};