// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { CreateEMailUserData, CreateEMailUserError, CreateEMailUserResponse2 } from './types.gen';

export const client = createClient(createConfig());

/**
 * Create an e-mail-based account
 */
export const createEMailUser = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<CreateEMailUserData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateEMailUserResponse2, CreateEMailUserError, ThrowOnError>({
        ...options,
        url: '/users/email'
    });
};