// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { CreateEmailUserData, CreateEmailUserError, CreateEmailUserResponse } from './types.gen';

/**
 * Create an e-mail-based account
 */
export const createEmailUser = (options?: Options<CreateEmailUserData>) => { return (options?.client ?? client).post<CreateEmailUserResponse, CreateEmailUserError>({
    ...options,
    url: '/users/email'
}); };