// This file is auto-generated by @hey-api/openapi-ts

export type CreateEMailUserRequest = {
    givenName: string;
    familyName: string;
    email: string;
    password: string;
};

export type CreateEMailUserResponse = {
    user: User;
    provider: UserProvider;
};

export type User = {
    /**
     * ID of the user
     */
    id: string;
    /**
     * Given name of the user
     */
    givenName: string;
    /**
     * Family name of the user
     */
    familyName: string;
};

export type UserProvider = {
    /**
     * ID of the user
     */
    userId: string;
    /**
     * The type of the auth provider
     */
    providerType: 'EMail';
    /**
     * The account id associated with the provider
     */
    accountId: string;
};

/**
 * The type of the auth provider
 */
export type providerType = 'EMail';

/**
 * The type of the auth provider
 */
export type UserProviderType = 'EMail';

export type CreateEMailUserData = {
    body?: CreateEMailUserRequest;
};

export type CreateEMailUserResponse2 = (CreateEMailUserResponse);

export type CreateEMailUserError = unknown;