// This file is auto-generated by @hey-api/openapi-ts

export type UserProviderType = 'EMail';

export type User = {
    /**
     * ID of the user
     */
    id: string;
    /**
     * Given name of the user
     */
    givenName: string;
    /**
     * Family name of the user
     */
    familyName: string;
};

export type UserProvider = {
    /**
     * ID of the user
     */
    userId: string;
    providerType: 'EMail';
    /**
     * The account id associated with the provider
     */
    accountId: string;
};

export type providerType = 'EMail';

export type CreateEMailUserRequest = {
    givenName: string;
    familyName: string;
    email: string;
    password: string;
};

export type CreateEMailUserResponse = {
    user: User;
    provider: UserProvider;
};

export type CreateEmailUserData = {
    body?: CreateEMailUserRequest;
};

export type CreateEmailUserResponse = CreateEMailUserResponse;

export type CreateEmailUserError = unknown;

export type $OpenApiTs = {
    '/users/': {
        post: {
            req: CreateEmailUserData;
            res: {
                /**
                 * Default Response
                 */
                '200': CreateEMailUserResponse;
            };
        };
    };
};